### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [terryllowery/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by terryllowery** [comment]
Hello Michael,
I added the viewport meta tag to the application.html.erb. 
Let me know if that is what we where looking for. 

Thanks, 
Terry

**Comment by Mikeysax** [comment]
:+1:
